log:
  format: '[%(levelname)s] %(asctime)s

    %(message)s'
  stream: true
  stream_level: 10
  file: ./logs
  file_level: 20
server:
  port: 8080
services: null
dict:
  a: 1
  b: 2
  c: 3
test: 卧槽
