log:
  name: microserv
  format: '[%(levelname)s] %(asctime)s

    %(message)s'
  stream: true
  stream_level: 10
  save_path: ./logs
  file_level: 20
server:
  port: 8080
services:
  hello_json:
    module: /mnt/d/GitHub/HttpMicroService/examples/hello.py
    entrypoint: hello_json
    response_type: json
  hello:
    module: /mnt/d/GitHub/HttpMicroService/examples/hello.py
    entrypoint: hello
    response_type: plain
